{
    "name": "Real Estate",
    "summary": "Test description",
    "version": "19.0.0.0.0",
    "author": "Andrea",
    "license": "LGPL-3",
    "depends": ["base"],
    "data": [
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "views/estate_property_views.xml",
        "views/estate_property_type_views.xml",
        "views/estate_property_offer_views.xml",
        "views/estate_property_tag_views.xml",
        "views/estate_menus.xml",
    ],
    "demo": ["demo/demo.xml"],
    "installable": True,
    "application": True,
}
